api:
  - changed-files:
      - any-glob-to-any-file: "services/**"
ui:
  - changed-files:
      - any-glob-to-any-file: "apps/**"
docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
seed:
  - changed-files:
      - any-glob-to-any-file: "seed/**"
ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**"
