name: "✨ Feature"
description: "Demande d'évolution"
labels: ["feature"]
body:
  - type: textarea
    id: goal
    attributes:
      label: Objectif
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Périmètre
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Critères d'acceptation
    validations:
      required: true
